name: Deploy to aws EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Push to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Deploy and run app with PM2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 51.21.196.192
          username: ubuntu
          key: ${{ secrets.PRIVATE_SSH_KEY }}
          port: 22
          script: |
            # Go to project directory (adjust if different)
            cd ~/cicd

            # Pull latest code
            git pull origin main

            # Install dependencies
            npm install

            # Build the project
            npm run build

            # Install PM2 if not installed
            if ! command -v pm2 &> /dev/null
            then
              npm install -g pm2
            fi

            # Stop existing app if running
            pm2 delete cicd || true

            # Start app using PM2
            pm2 start npm --name cicd -- run start

            # Save the process list to auto-start on reboot
            pm2 save
